# Generated by Django 5.2.16 on 2026-07-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('email', models.TextField(null=True, unique=True)),
                ('phone', models.TextField(default='', null=True)),
                ('birthday', models.TextField(default='', null=True)),
                ('role', models.TextField(default='Học viên', null=True)),
                ('password', models.TextField(null=True)),
                ('streak', models.IntegerField(default=0, null=True)),
                ('certificates', models.IntegerField(default=0, null=True)),
                ('gems', models.IntegerField(default=0, null=True)),
                ('xp', models.IntegerField(default=0, null=True)),
                ('questionnaire_completed', models.IntegerField(default=0, null=True)),
                ('last_study_date', models.DateField(null=True)),
                ('oauth_provider', models.TextField(null=True)),
                ('oauth_provider_id', models.TextField(null=True)),
                ('avatar', models.TextField(default='', null=True)),
                ('is_verified', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(null=True)),
                ('data_json', models.JSONField(null=True)),
                ('created_at', models.TextField(null=True)),
            ],
            options={
                'db_table': 'surveys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('pk', models.CompositePrimaryKey('follower_id', 'followee_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('follower_id', models.IntegerField()),
                ('followee_id', models.IntegerField()),
                ('created_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'user_follows',
                'managed': False,
            },
        ),
    ]
