# Generated by Django 5.2.16 on 2026-07-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(null=True)),
                ('type', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('body', models.TextField(null=True)),
                ('ref_type', models.TextField(null=True)),
                ('ref_id', models.IntegerField(null=True)),
                ('is_read', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'notifications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email_notif', models.IntegerField(default=1, null=True)),
                ('push_notif', models.IntegerField(default=0, null=True)),
                ('study_remind', models.IntegerField(default=1, null=True)),
                ('content_update', models.IntegerField(default=0, null=True)),
            ],
            options={
                'db_table': 'notification_settings',
                'managed': False,
            },
        ),
    ]
