# Generated by Django 5.2.16 on 2026-07-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('course_id', models.TextField()),
                ('status', models.TextField(default='generated', null=True)),
                ('questions_json', models.JSONField()),
                ('created_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'quizzes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewQuizResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quiz_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('score', models.IntegerField()),
                ('total', models.IntegerField()),
                ('answers_json', models.JSONField()),
                ('submitted_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'review_quiz_results',
                'managed': False,
            },
        ),
    ]
