# Generated by Django 5.2.16 on 2026-07-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('title', models.TextField(null=True)),
                ('subtitle', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('image', models.TextField(null=True)),
                ('level', models.TextField(null=True)),
                ('duration', models.TextField(null=True)),
                ('students', models.TextField(null=True)),
                ('rating', models.FloatField(null=True)),
                ('lessons', models.IntegerField(null=True)),
                ('color', models.TextField(null=True)),
                ('accent_color', models.TextField(null=True)),
                ('tag', models.TextField(null=True)),
                ('instructor_id', models.IntegerField(null=True)),
                ('xp_reward', models.IntegerField(default=0, null=True)),
                ('is_published', models.BooleanField(default=True, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('content_meta', models.JSONField(null=True)),
            ],
            options={
                'db_table': 'courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseRating',
            fields=[
                ('pk', models.CompositePrimaryKey('user_id', 'course_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('course_id', models.TextField()),
                ('rating', models.IntegerField()),
                ('created_at', models.TextField(null=True)),
            ],
            options={
                'db_table': 'course_ratings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('pk', models.CompositePrimaryKey('user_id', 'course_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('course_id', models.TextField()),
                ('progress', models.IntegerField(default=0, null=True)),
                ('completed_lessons', models.IntegerField(default=0, null=True)),
                ('time_spent', models.TextField(default='0h', null=True)),
                ('last_lesson', models.TextField(default='', null=True)),
                ('next_lesson', models.TextField(default='', null=True)),
                ('status', models.TextField(default='active', null=True)),
                ('enrolled_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'enrollments',
                'managed': False,
            },
        ),
    ]
