# Generated by Django 5.2.16 on 2026-07-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(null=True)),
                ('source', models.TextField(default='template', null=True)),
                ('generated_from_survey_id', models.IntegerField(null=True)),
                ('title', models.TextField(null=True)),
                ('icon', models.TextField(null=True)),
                ('color', models.TextField(null=True)),
                ('nodes_json', models.JSONField(default=list, null=True)),
                ('edges_json', models.JSONField(default=list, null=True)),
                ('mermaid_def', models.TextField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'roadmaps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoadmapProgress',
            fields=[
                ('pk', models.CompositePrimaryKey('user_id', 'roadmap_id', 'item_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('roadmap_id', models.TextField()),
                ('item_id', models.TextField()),
                ('done', models.BooleanField(default=False, null=True)),
                ('completed_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'roadmap_progress',
                'managed': False,
            },
        ),
    ]
