# Generated by Django 5.2.16 on 2026-07-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('description', models.TextField(null=True)),
                ('icon', models.TextField(null=True)),
                ('condition_type', models.TextField()),
                ('condition_value', models.IntegerField()),
            ],
            options={
                'db_table': 'achievements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('pk', models.CompositePrimaryKey('user_id', 'achievement_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('achievement_id', models.IntegerField()),
                ('awarded_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'user_achievements',
                'managed': False,
            },
        ),
    ]
