# Generated by Django 5.2.16 on 2026-07-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_id', models.IntegerField(null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('parent_comment_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('pk', models.CompositePrimaryKey('comment_id', 'user_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('comment_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('reaction_type', models.TextField(default='like')),
                ('created_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'comment_likes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(null=True)),
                ('category', models.TextField(default='discuss', null=True)),
                ('title', models.TextField(default='', null=True)),
                ('content', models.TextField()),
                ('like_count', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'posts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('pk', models.CompositePrimaryKey('post_id', 'user_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('post_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('reaction_type', models.TextField(default='like')),
                ('created_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'post_likes',
                'managed': False,
            },
        ),
    ]
