# Generated by Django 5.2.16 on 2026-07-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField(default='', null=True)),
                ('xp_reward', models.IntegerField(default=50, null=True)),
                ('course_id', models.TextField(null=True)),
                ('sort_order', models.IntegerField(default=0, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('correct_condition', models.TextField(default='', null=True)),
                ('correct_action', models.TextField(default='', null=True)),
            ],
            options={
                'db_table': 'missions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserDailyXpLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(null=True)),
                ('log_date', models.DateField()),
                ('xp_earned', models.IntegerField(default=0, null=True)),
            ],
            options={
                'db_table': 'user_daily_xp_logs',
                'managed': False,
            },
        ),
    ]
